# Generated by Django 5.0 on 2023-12-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
