# Generated by Django 5.0 on 2023-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisments', '0002_reply_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('Танки', 'Tank'), ('Хилер', 'Healer'), ('Дэмэдж дилер', 'Damage dealer'), ('Трейдер', 'Trader'), ('Гилдмастер', 'Guild master'), ('Квестгивер', 'Quest giver'), ('Кузнецы', 'Warsmith'), ('Кожевники', 'Tanner'), ('Зельевары', 'Potion maker'), ('Мастера заклинаний', 'Spell master')], default=None, max_length=18),
        ),
    ]
